version: '3'

services:
  web:
    container_name: "web"
    build:
      context: ./
      dockerfile: web.docker
    links:
      - app
    volumes:
      - .:/var/www
    ports:
      - 8080:80
  app:
    container_name: "app"
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - .:/var/www
    depends_on:
      - database
    links:
      - database
    environment:
      DB_HOST: database
      DB_DATABASE: vcexchange
      DB_USERNAME: root
      DB_PASSWORD: secret
  database:
    container_name: "database"
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: vcexchange
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret